platform :ios, '10.0'
use_frameworks!

target 'LPParseConnect_Example' do
  pod 'LPParseConnect', :path => '../'
  pod 'Parse'

  target 'LPParseConnect_Tests' do
    inherit! :search_paths
    
  end
end
