platform :ios, '10.0'
use_frameworks!

target 'LPParseConnect_Example' do
  pod 'LPParseConnect', :path => '../'
  pod 'Parse'
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'
  pod 'LPCommonUI', :git => 'https://github.com/Launchpeer/LPCommonUI_iOS.git'
  target 'LPParseConnect_Tests' do
    inherit! :search_paths
    
  end
end
